# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-improvement-app"
client_id = "06b5974e139176a4b8983cc94da7a674"
application_url = "http://localhost:5173"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "http://localhost:5173/auth/callback",
  "http://localhost:5173/auth/shopify/callback",
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testmustadatokmak.myshopify.com"