name: Deploy Shopify App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shopify-app:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 5.189.174.110
        username: mustafa
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/shopify-app:latest
          sudo docker stop shopify-app || true
          sudo docker rm shopify-app || true
          sudo docker run -d -p 3003:3000 --name shopify-app --restart always \
            -e NODE_ENV=production \
            -e SHOPIFY_APP_URL=https://5.189.174.110:3003 \
            -e SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }} \
            -e SHOPIFY_API_SECRET=${{ secrets.SHOPIFY_API_SECRET }} \
            -e SCOPES=read_products,write_products \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e IMPROVEMENT_API_URL=${{ secrets.IMPROVEMENT_API_URL }} \
            -e IMPROVEMENT_API_KEY=${{ secrets.IMPROVEMENT_API_KEY }} \
            -e ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} \
            ${{ secrets.DOCKER_USERNAME }}/shopify-app:latest